- name: fetch prometheus
  shell: "ls /etc/systemd/system|grep prometheus|wc -l"
  register: prometheus_status
  tags:
  - prometheus_installation

- name: Download and unarchive prometheus
  unarchive:
    src: https://github.com/prometheus/prometheus/releases/download/v2.11.1/prometheus-2.11.1.linux-amd64.tar.gz
    dest: /home/ec2-user
    remote_src: yes
  tags:
   - prometheus_installation

- name: Rename prometheus directory
  shell: "mv /home/ec2-user/prometheus-* /home/ec2-user/prometheus"
  tags:
   - prometheus_installation

- name: Add prometheus config
  template:
    src: prometheus.yaml.j2
    dest: '/home/ec2-user/prometheus.yaml' 
    owner: root
    group: root
    mode: 0755
  tags:
  - prometheus

- name: Add prometheus.service
  template:
    src: prometheus.service.j2
    dest: '/etc/systemd/system/prometheus.service' 
    owner: root
    group: root
    mode: 0755
  tags:
  - prometheus

- name: Reload systemd
  systemd:
    daemon_reload: yes
  tags:
  - prometheus

- name: Start systemd prometheus
  systemd:
    name: prometheus
    state: started
    enabled: yes
  tags:
  - prometheus